name: PHPUnit Tests

on:
  push:
    branches: [ '*' ]

jobs:
  tests:

    runs-on: ubuntu-latest
    
    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1'
    - uses: actions/checkout@v3
    - name: Composer dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Directory permissions
      run: chmod -R 777 storage
    - name: PHPUnit Tests
      run: vendor/bin/phpunit
